### ISSUE TITLE
Unable to connect to an H2 database on 1.11

### ISSUE THREAD

**Issue by Ironic8b498** [TheE/MyWarp#115]
Still got 3 other plugins holding me back for upgrading this one Server to 1.11, but my first attempt was with build #127 and not boot up error

`````
[22:13:26] [Server thread/ERROR]: [MyWarp] Failed to initialize warp storage.
me.taylorkelly.mywarp.warp.storage.StorageInitializationException: Failed to execute migration process.
	at me.taylorkelly.mywarp.warp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:105) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.MyWarp.initialize(MyWarp.java:115) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.onEnable(MyWarpPlugin.java:118) [mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot-1.11.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.11.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.11.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-16c940b-0805f60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: me.taylorkelly.mywarp.internal.flyway.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource
	at me.taylorkelly.mywarp.internal.flyway.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.execute(Flyway.java:1326) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.repair(Flyway.java:1106) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.warp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:102) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	... 13 more
Caused by: me.taylorkelly.mywarp.internal.h2.jdbc.JdbcSQLException: (Message 90020 not found) [90020-176]
	at me.taylorkelly.mywarp.internal.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.message.DbException.get(DbException.java:178) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.message.DbException.get(DbException.java:154) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.store.FileLock.getExceptionAlreadyInUse(FileLock.java:462) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.store.FileLock.lockFile(FileLock.java:356) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.store.FileLock.lock(FileLock.java:136) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.engine.Database.open(Database.java:622) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.engine.Database.openDatabase(Database.java:260) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.engine.Database.<init>(Database.java:254) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.engine.Engine.openSession(Engine.java:57) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.engine.Engine.openSession(Engine.java:164) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.engine.Engine.createSessionAndValidate(Engine.java:142) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.engine.Engine.createSession(Engine.java:125) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.engine.Engine.createSession(Engine.java:27) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.h2.Driver.connect(Driver.java:74) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_91]
	at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[?:1.8.0_91]
	at me.taylorkelly.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.initiate(SingleConnectionDataSource.java:170) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.getConnection(SingleConnectionDataSource.java:84) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.flyway.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.execute(Flyway.java:1326) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.repair(Flyway.java:1106) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	at me.taylorkelly.mywarp.warp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:102) ~[mywarp-bukkit-3.0-SNAPSHOT-all-%23129.jar:3.0-SNAPSHOT+jenkins-b129.git-a87206e395]
	... 13 more
`````

**Comment by TheE** [comment]
I cannot reproduce this with 1.11.

From the log you posted, it looks like the H2 database engine fails to connect to the database due to error `90020`. This error indicates that the database is already used by another process (see [here](http://www.h2database.com/javadoc/org/h2/api/ErrorCode.html#c90020)).

Since I cannot reproduce the error, it does not appear to be specifically related to version 1.11. Are you sure that no process was accessing the database? Was the server properly shut down before testing?

**Comment by TheE** [comment]
If you have no idea why the database might be used by another process, you could also try to switch to MySQL or - with recent Spigot versions - SQLite instead of H2.

I can help you to properly configure your `config.yml` if needed.

**Comment by Ironic8b498** [comment]
I was getting you the info in my config.yml file when it hit me, Since my first attempt to update to 1.11 I had to many broken plugins, I converted back to 1.10.2 and then my chest were invisible and items in chest were gone, so I used an archive to create another server and missed changing path to the H2 database. works now, thanks for letting me know what the error was so I could figure it out
