### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by DutchUser** [TheE/MyWarp#69]
````
11 22:58:27 [Server] INFO ... 12 more
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.MyWarp.<init>(MyWarp.java:88) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:106) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.internal.flyway.core.Flyway.repair(Flyway.java:1203) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.internal.flyway.core.Flyway.execute(Flyway.java:1385) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.internal.flyway.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.getConnection(SingleConnectionDataSource.java:81) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.initiate(SingleConnectionDataSource.java:151) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_45]
15.11 22:58:27 [Server] INFO at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_45]
15.11 22:58:27 [Server] INFO at org.sqlite.JDBC.connect(JDBC.java:64) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
15.11 22:58:27 [Server] INFO at org.sqlite.JDBC.createConnection(JDBC.java:74) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
15.11 22:58:27 [Server] INFO Caused by: java.sql.SQLException: invalid database address: jdbc:h2:/plugins/MyWarp/warps
15.11 22:58:27 [Server] INFO ... 12 more
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.MyWarp.<init>(MyWarp.java:88) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:106) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.internal.flyway.core.Flyway.repair(Flyway.java:1203) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.internal.flyway.core.Flyway.execute(Flyway.java:1385) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.internal.flyway.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO Caused by: me.taylorkelly.mywarp.internal.flyway.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource
15.11 22:58:27 [Server] INFO ... 12 more
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.MyWarp.<init>(MyWarp.java:88) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:109) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO Caused by: me.taylorkelly.mywarp.storage.StorageInitializationException: Failed to execute migration process.
15.11 22:58:27 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
15.11 22:58:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
15.11 22:58:27 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
15.11 22:58:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
15.11 22:58:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
15.11 22:58:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
15.11 22:58:27 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
15.11 22:58:27 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
15.11 22:58:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
15.11 22:58:27 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
15.11 22:58:27 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.onEnable(MyWarpPlugin.java:177) [MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO at me.taylorkelly.mywarp.MyWarp.<init>(MyWarp.java:94) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
15.11 22:58:27 [Server] INFO me.taylorkelly.mywarp.InitializationException: Failed to get a connection to the database.
15.11 22:58:27 [Server] ERROR A critical failure has been encountered and MyWarp is unable to continue. MyWarp will be disabled.
````

**Comment by TheE** [comment]
Seems like your database URL is messed up for some reason. Try removing `storage.url` from the configuration and restarting your server to regenerate the entry.

**Comment by DutchUser** [comment]
I not have "storage.url" in my config

http://pastebin.com/F8qdrVBp

**Comment by TheE** [comment]
Yes, you do, line 10.

**Comment by DutchUser** [comment]
If i remove that line and reload MyWarp i got again this error:

http://pastebin.com/Y3UVmX6W

**Comment by DutchUser** [comment]
I make an backup of my db's and remobe then. After that he works. So maybay an issue with he .db's?

**Comment by DutchUser** [comment]
I think that i found the issu that caused this. The day that this happend i removed some worlds that have mywarp warps after the restart the db's are not working anymore. When i remove de db's the plugin working again.

Maybay an H2 bug or something.

**Comment by DutchUser** [comment]
bump,
