### ISSUE TITLE
unable to use warp command due to invalid locale format

### ISSUE THREAD

**Issue by voigtman** [TheE/MyWarp#91]
I have a handful of players who for unknown reasons to them (many are kids and perhaps parents set up some kind of protection for them) they can't issue the warp command because of their location... in this case "lol_US" Why would mywarp even need to know this information?

`[16:20:47] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mw' in plugin MyWarp v3.0-beta-3+jenkins-b98.git-623f42c
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1078) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.chat(CraftPlayer.java:237) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at it.mri.mycommand.execute.DispatchCommands.ExecuteCommands(DispatchCommands.java:635) [MyCommand-v5.1.6.jar:?]
	at it.mri.mycommand.execute.DispatchCommands.PerformMycmdCommands(DispatchCommands.java:459) [MyCommand-v5.1.6.jar:?]
	at it.mri.mycommand.execute.DispatchCommands.ExecuteMyCommandCommands(DispatchCommands.java:202) [MyCommand-v5.1.6.jar:?]
	at it.mri.mycommand.listener.PreprocessEvent.onPlayerCommandPreprocess(PreprocessEvent.java:110) [MyCommand-v5.1.6.jar:?]
	at sun.reflect.GeneratedMethodAccessor276.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) [PerWorldPlugins-v1.9.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins-v1.9.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1078) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.chat(CraftPlayer.java:237) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at it.mri.mycommand.execute.DispatchCommands.ExecuteCommands(DispatchCommands.java:635) [MyCommand-v5.1.6.jar:?]
	at it.mri.mycommand.execute.DispatchCommands.PerformMycmdCommands(DispatchCommands.java:459) [MyCommand-v5.1.6.jar:?]
	at it.mri.mycommand.execute.DispatchCommands.ExecuteMyCommandCommands(DispatchCommands.java:202) [MyCommand-v5.1.6.jar:?]
	at it.mri.mycommand.listener.PreprocessEvent.onPlayerCommandPreprocess(PreprocessEvent.java:110) [MyCommand-v5.1.6.jar:?]
	at sun.reflect.GeneratedMethodAccessor276.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) [PerWorldPlugins-v1.9.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins-v1.9.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.IllegalArgumentException: Invalid locale format: lol_US
	at org.apache.commons.lang.LocaleUtils.toLocale(LocaleUtils.java:99) ~[SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at me.taylorkelly.mywarp.bukkit.util.parametric.ReflectiveLocaleResolver.resolve(ReflectiveLocaleResolver.java:99) ~[?:?]
	at me.taylorkelly.mywarp.bukkit.BukkitPlayer.getLocale(BukkitPlayer.java:119) ~[?:?]
	at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.onCommand(MyWarpPlugin.java:276) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[SkyBlock-1.8.8.jar:git-Spigot-0359393-9cd1111]
	... 45 more`

**Comment by TheE** [comment]
Please update to the latest devBuild, I fixed the issue a while ago.

MyWarp is fully localised; it accesses each player's locale (the locale configured in the player's client under options -> language...) to determine which localisation should be used when sending messages to the player.

**Comment by voigtman** [comment]
Thank you I was still on build 103.
they're using the vanilla minecraft client, i'll let them know and update this. Thanks
