### ISSUE TITLE
an strange error

### ISSUE THREAD

**Issue by DutchUser** [TheE/MyWarp#96]
```
[00:15:07] [Server thread/ERROR]: [MyWarp] A critical failure has been encountered and MyWarp is unable to continue. MyWarp will be disabled.
me.taylorkelly.mywarp.InitializationException: Failed to get a connection to the database.
	at me.taylorkelly.mywarp.MyWarp.<init>(MyWarp.java:94) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.onEnable(MyWarpPlugin.java:177) [MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: me.taylorkelly.mywarp.storage.StorageInitializationException: Failed to execute migration process.
	at me.taylorkelly.mywarp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:109) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	at me.taylorkelly.mywarp.MyWarp.<init>(MyWarp.java:88) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	... 12 more
Caused by: me.taylorkelly.mywarp.internal.flyway.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource
	at me.taylorkelly.mywarp.internal.flyway.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.execute(Flyway.java:1385) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.repair(Flyway.java:1203) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	at me.taylorkelly.mywarp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:106) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	at me.taylorkelly.mywarp.MyWarp.<init>(MyWarp.java:88) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	... 12 more
Caused by: java.sql.SQLException: invalid database address: jdbc:h2:/home/minecraft/multicraft/servers/server5919/plugins/MyWarp/warps
	at org.sqlite.JDBC.createConnection(JDBC.java:74) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.sqlite.JDBC.connect(JDBC.java:64) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_45]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_45]
	at me.taylorkelly.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.initiate(SingleConnectionDataSource.java:151) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	at me.taylorkelly.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.getConnection(SingleConnectionDataSource.java:81) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	at me.taylorkelly.mywarp.internal.flyway.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.execute(Flyway.java:1385) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	at me.taylorkelly.mywarp.internal.flyway.core.Flyway.repair(Flyway.java:1203) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	at me.taylorkelly.mywarp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:106) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	at me.taylorkelly.mywarp.MyWarp.<init>(MyWarp.java:88) ~[MyWarp.jar:3.0-beta-3+jenkins-b98.git-623f42c]
	... 12 more
[00:15:07] [Server thread/INFO]: [MyWarp] Disabling MyWarp v3.0-beta-3+jenkins-b98.git-623f42c
[00:15:07] [Server thread/WARN]: Plugin MyWarp v3.0-beta-3+jenkins-b98.git-623f42c tried to register permission 'mywarp.cmd.assets' but it's already registered
java.lang.IllegalArgumentException: The permission mywarp.cmd.assets is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:599) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
[00:15:07] [Server thread/WARN]: Plugin MyWarp v3.0-beta-3+jenkins-b98.git-623f42c tried to register permission 'mywarp.cmd.*' but it's already registered
java.lang.IllegalArgumentException: The permission mywarp.cmd.* is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:599) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
[00:15:07] [Server thread/WARN]: Plugin MyWarp v3.0-beta-3+jenkins-b98.git-623f42c tried to register permission 'mywarp.sign.create' but it's already registered
java.lang.IllegalArgumentException: The permission mywarp.sign.create is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:599) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
[00:15:07] [Server thread/WARN]: Plugin MyWarp v3.0-beta-3+jenkins-b98.git-623f42c tried to register permission 'mywarp.sign.*' but it's already registered
java.lang.IllegalArgumentException: The permission mywarp.sign.* is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:599) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
[00:15:07] [Server thread/WARN]: Plugin MyWarp v3.0-beta-3+jenkins-b98.git-623f42c tried to register permission 'mywarp.timer.disobey.warmup-abort.*' but it's already registered
java.lang.IllegalArgumentException: The permission mywarp.timer.disobey.warmup-abort.* is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:599) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
[00:15:07] [Server thread/WARN]: Plugin MyWarp v3.0-beta-3+jenkins-b98.git-623f42c tried to register permission 'mywarp.timer.disobey' but it's already registered
java.lang.IllegalArgumentException: The permission mywarp.timer.disobey is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:599) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
[00:15:07] [Server thread/WARN]: Plugin MyWarp v3.0-beta-3+jenkins-b98.git-623f42c tried to register permission 'mywarp.override.*' but it's already registered
java.lang.IllegalArgumentException: The permission mywarp.override.* is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:599) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
[00:15:07] [Server thread/WARN]: Plugin MyWarp v3.0-beta-3+jenkins-b98.git-623f42c tried to register permission 'mywarp.*' but it's already registered
java.lang.IllegalArgumentException: The permission mywarp.* is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:599) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
```

Someone reported to my that the /warp command was not working and whenm i looked in console its seems that the plugin is disable for an reason. I asume for the error above this. When i restart the server mywarp was working again but still. I want to report this so that i know what cause this. (Multiple plugins gives error when this one was in console)

**Comment by DutchUser** [comment]
UPDATE: It soms that %70 of our plugins give BIG amount of erros so as this one. But still. Can you maybe see if the issue is caused by the server itself?

**Comment by TheE** [comment]
It looks like MyWarp was not properly disabled and then re-enabled. This might happen if you use the `/reload` command or third-party plugin reloaders.

Generell avoid the `/reload` command. It harms the server's performance (not properly unloaded plugins remain within the RAM), many plugins do not work with it and, even if they should work like MyWarp, there may be errors such as yours. It is generally quicker to simply restart the server instead of reloading it.

**Comment by DutchUser** [comment]
I not used /reload I was not online when this happend. I was joining an player come with the issue to my after that i looked in console en schrol above an saw the big amount of errors of multple plugins

**Comment by TheE** [comment]
Very strange. It definitely looks like MyWarp was not properly unloaded: permissions which MyWarp registers at startup and unregistered at shutdown were already defined - this cannot happen normally.

Personally I would suspect some kind of issue within Spigot or Bukkit. But if this does not happen again you should be fine.

**Comment by DutchUser** [comment]
Oke. I will stay looking for this. Thx for you fast reaction :)
