### ISSUE TITLE
Any warps can be overwritten by other players

### ISSUE THREAD

**Issue by Ghostlyr** [TheE/MyWarp#99]
Critical issue: any foreign player can create warp with same name (in the same case!) and overwritte already existing warp.

Players have not admin permissions:
![4656445665](https://cloud.githubusercontent.com/assets/8511068/14775066/fb5a0084-0add-11e6-8960-7c17cc6cdc60.png)

Last development version. 2.x versions did not have this problem.
MC 1.7.10 (Thermos 56 on bukkit R0.1)

**Comment by Ghostlyr** [comment]
Thanks!
But what happened with build-server https://thee140.ci.cloudbees.com/job/mywarp3_bukkit/ ? I get 404 error from apache...

**Comment by TheE** [comment]
For some reason cloudbees CI stopped working (wtf?). Currently I have no time to investigate, so you either need to build by yourself or use the JAR file provided below:

[mywarp-bukkit-3.0-SNAPSHOT-all.jar.zip](https://github.com/TheE/MyWarp/files/234092/mywarp-bukkit-3.0-SNAPSHOT-all.jar.zip)

**Comment by Ghostlyr** [comment]
Hmmm. I get this error:

```
[MyWarp] Failed to load warps from the database.
java.lang.IllegalArgumentException: A warp with the name '{}' does already exist!
	at guava10.com.google.common.base.Preconditions.checkArgument(Preconditions.java:88) ~[Preconditions.class:1.7.10-1614.54]
	at me.taylorkelly.mywarp.warp.MemoryWarpManager.add(MemoryWarpManager.java:41) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.warp.MemoryWarpManager.populate(MemoryWarpManager.java:48) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.warp.StorageWarpManager.populate(StorageWarpManager.java:76) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.warp.EventfulWarpManager.populate(EventfulWarpManager.java:82) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.MyWarp$2.onSuccess(MyWarp.java:259) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.MyWarp$2.onSuccess(MyWarp.java:255) [mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at guava10.com.google.common.util.concurrent.Futures$7.run(Futures.java:1072) [Futures$7.class:1.7.10-1614.54]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [CraftTask.class:1.7.10-1614.54]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.54]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:895) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

I have not found "null" warp on my database.. With older build all works fine

**Comment by TheE** [comment]
Sorry, I messed up the error message. Please try the build attached to this comment for a proper message.

It seems like there are multiple warps of the same name in your database. This should not happen but it does, for some reason. What storage option are you using (H2, MySQL...)?

Are you able to manually remove these duplicates from the `warp` table within your database?

[mywarp-bukkit-3.0-SNAPSHOT-all.jar.zip](https://github.com/TheE/MyWarp/files/234357/mywarp-bukkit-3.0-SNAPSHOT-all.jar.zip)

**Comment by Ghostlyr** [comment]
Not found any dublicates.
I tried to remove every "aready existing" warp on older version, but after every start i a new error with new warp:


```
```

```
[MyWarp] Failed to load warps from the database.
java.lang.IllegalArgumentException: A warp with the name 'e' does already exist!
	at guava10.com.google.common.base.Preconditions.checkArgument(Preconditions.java:115) ~[Preconditions.class:1.7.10-1614.54]
	at me.taylorkelly.mywarp.warp.MemoryWarpManager.add(MemoryWarpManager.java:41) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.warp.MemoryWarpManager.populate(MemoryWarpManager.java:48) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.warp.StorageWarpManager.populate(StorageWarpManager.java:76) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.warp.EventfulWarpManager.populate(EventfulWarpManager.java:82) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.MyWarp$2.onSuccess(MyWarp.java:259) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.MyWarp$2.onSuccess(MyWarp.java:255) [mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at guava10.com.google.common.util.concurrent.Futures$7.run(Futures.java:1072) [Futures$7.class:1.7.10-1614.54]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [CraftTask.class:1.7.10-1614.54]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.54]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:895) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```
It was a only one warp with "e" name. List warps on old build:
![465456456](https://cloud.githubusercontent.com/assets/8511068/14782300/59e85796-0b0a-11e6-87f7-4682eed070ed.png)
```
[MyWarp] Failed to load warps from the database.
java.lang.IllegalArgumentException: A warp with the name 'hereibuildpvp' does already exist!
	at guava10.com.google.common.base.Preconditions.checkArgument(Preconditions.java:115) ~[Preconditions.class:1.7.10-1614.54]
	at me.taylorkelly.mywarp.warp.MemoryWarpManager.add(MemoryWarpManager.java:41) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.warp.MemoryWarpManager.populate(MemoryWarpManager.java:48) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.warp.StorageWarpManager.populate(StorageWarpManager.java:76) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.warp.EventfulWarpManager.populate(EventfulWarpManager.java:82) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.MyWarp$2.onSuccess(MyWarp.java:259) ~[mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at me.taylorkelly.mywarp.MyWarp$2.onSuccess(MyWarp.java:255) [mywarp-bukkit-3.0-SNAPSHOT-all.jar:?]
	at guava10.com.google.common.util.concurrent.Futures$7.run(Futures.java:1072) [Futures$7.class:1.7.10-1614.54]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [CraftTask.class:1.7.10-1614.54]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.54]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:895) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```
This warp is too unique, not dublicated...

**Comment by TheE** [comment]
Fixed.

[mywarp-bukkit-3.0-SNAPSHOT-all.jar.zip](https://github.com/TheE/MyWarp/files/234441/mywarp-bukkit-3.0-SNAPSHOT-all.jar.zip)

**Comment by Ghostlyr** [comment]
Heh, thanks a lot
